### ISSUE TITLE
Failed on travis-ci

### ISSUE THREAD

**Issue by koron** [vim-jp/ctags#13]
> Testing TAGS output...ctags.ref: Unexpected end of file: Test/ocaml_empty.ml

from https://travis-ci.org/vim-jp/ctags/builds/20679028

**Comment by mattn** [comment]
個人的にはuniversal-ctagsをオフィシャルとして扱い、あちらは既にtravisが導入されているのでこちらが新たにアクションを起こすつもりはないです。
