### ISSUE TITLE
Allow "#..." comments in .ctags

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/ctags#6]
[Exuberant Ctags / Patches / #82 Support for comments in .ctags files](http://sourceforge.net/p/ctags/patches/82/)
https://github.com/fishman/ctags/commit/06b400a76d958438d457ee737e491b499571bd22
https://github.com/fishman/ctags/commit/06b400a76d958438d457ee737e491b499571bd22.patch

**Comment by mattn** [comment]
universal-ctags を本家と位置付けるのでこちらは閉じます。
