### ISSUE TITLE
本家への連絡

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/ctags#7]
本家の[Mailing Lists](http://sourceforge.net/p/ctags/mailman/ctags-devel/)に 
[[Ctags-devel] Regarding my absence ](http://sourceforge.net/p/ctags/mailman/message/31524274/)
こんな投稿がなされました。

今後の対応を含めて、連絡するなど何らかの行動をおこした方がいいのではないでしょうか。

**Comment by mattn** [comment]
universal-ctagsを本家と位置付けたいと思います。
